name: KitPvP
author:
  - Cervinakuy
  - AoneHax
main: com.planetgallium.kitpvp.Game
version: 2.2.5
description: 职业战争
website: happycraft.cc
softdepend: [PlaceholderAPI, WorldGuard]
api-version: 1.13

commands:
   kitpvp:
     description: Main command.
     aliases: [kp, kit-pvp]
   ckit:
     description: Select a kit.
   cspawn:
     description: Teleports you to the spawn.
   ckits:
     description: View all available kits.
   cstats:
     description: View your stats.